pages:
  image: debian:bullseye-slim
  before_script:
    - apt update -y
    - apt install -y python3 python3-yaml
  script:
    - tools/izzy.py
    - tools/buildcache.py
  artifacts:
    paths:
      - public
  only:
    - master
