image: debian:bookworm-slim

stages:
  - test
  - deploy

black:
  stage: test
  script:
    - apt-get update -y
    - apt-get -qy install black
    - black --check --diff --color */*.py

lint:
  stage: test
  before_script:
    - apt update -y
    - apt install -y yamllint
  script:
    - yamllint */*.yml

validate:
  stage: test
  before_script:
    - apt update -y
    - apt install -y npm
    - npm install -g ajv-cli
  script:
    - find suss/ -type f -name '*.yml' | xargs -n 1 ajv validate -s schemas/schema.json -d

test:
  stage: test
  before_script:
    - apt update -y
    - apt install -y python3 python3-pytest python3-validators python3-yaml
  script:
    - tools/buildcache.py
    - pytest-3

pages:
  stage: deploy
  before_script:
    - apt update -y
    - apt install -y python3 python3-yaml
  script:
    - tools/izzy.py
    - tools/buildcache.py
  artifacts:
    paths:
      - public
  only:
    - master
